#!/usr/bin/env bash
# Capture what the robot is ACTUALLY running, into requirements.lock.txt.
#
# Read-only: it installs nothing, upgrades nothing and touches no site-packages. Safe to run on a
# live robot mid-demo. requirements.txt lists what the code imports; this lists the exact versions
# behind those imports, which is what an SD-card rebuild has to reproduce.
#
# Usage:  ./scripts/freeze_requirements.sh    (from the repo root, on the Jetson)

set -euo pipefail

cd "$(dirname "$0")/.."
OUT="requirements.lock.txt"

# Wheels that must NOT be reinstalled from PyPI on a Jetson: torch is hand-built with CUDA, and
# the rest are either JetPack-provided or have no working aarch64 wheel upstream.
JETSON_BUILT='^(torch|torchvision|torchaudio|onnxruntime-gpu|tensorrt|cuda-python|nvidia-|jetson-)'

{
    echo "# Generated by scripts/freeze_requirements.sh on $(date -Iseconds)"
    echo "# Host: $(uname -srm)  |  $(python3 --version)"
    echo "#"
    echo "# ⚠️  Lines marked [JETSON-BUILT] must NOT be reinstalled from PyPI — they are either"
    echo "#     hand-built with CUDA or provided by JetPack. Restoring them from this file with a"
    echo "#     plain 'pip3 install -r' will give you a CPU-only build."
    echo "#"
    python3 -m pip freeze 2>/dev/null | while IFS= read -r line; do
        if [[ "$line" =~ $JETSON_BUILT ]]; then
            echo "$line    # [JETSON-BUILT] do not reinstall from PyPI"
        else
            echo "$line"
        fi
    done
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)."
grep -c 'JETSON-BUILT' "$OUT" | xargs -I{} echo "  {} entries flagged as Jetson-built."
echo "Commit it. It is the only record of what this environment is."
